rootUrl: http://localhost:8080/components/vaadin-date-picker/test/visual/
gridUrl: http://localhost:4444/wd/hub
screenshotsDir: ./test/visual/screens
windowSize: 1024x768

system:
  plugins:
    polyserve:
      port: 8080
    sauce: true

browsers:
  chrome:
    desiredCapabilities:
      browserName: "chrome"
      version: "66.0"
      platform: "Windows 10"
