---
title: Other features
order: 3
layout: page
---

[[vaadin-date-picker.features]]
= Other Features

== Localization

The [vaadinelement]#vaadin-date-picker# element supports localization through its [propertyname]#i18n# property.

You can adjust the element to a specific language and date format by assigning the [propertyname]#i18n# property.
See the example below for the default values used when the property is not defined.

[source,javascript]
----
datePicker.i18n = {
  monthNames: [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November','December'
  ],
  weekdays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  firstDayOfWeek: 0,
  today: 'Today',
  cancel: 'Cancel',
  formatDate: function(date) {
    return (date.getMonth() + 1) + '/' + date.getDate() + '/' + date.getFullYear();
  }
}
----

* [propertyname]#i18n.monthNames# – An array of month names starting from January.
* [propertyname]#i18n.weekdays# – An array of short weekday names starting from Sunday.
* [propertyname]#i18n.firstDayOfWeek# – An integer for the first day of the week (0 = Sunday, 1 = Monday, etc.).
* [propertyname]#i18n.today# – Translation of the Today shortcut button text.
* [propertyname]#i18n.cancel# – Translation of the Cancel button text.
* [propertyname]#i18n.formatDate# – A function to format given [classname]#Date# object as [classname]#String#.

Once set, the [propertyname]#i18n# property affects how months and dates are displayed in the [vaadinelement]#vaadin-date-picker# dropdown as well as the language of the buttons in the element.


== Initial Position

When [vaadinelement]#vaadin-date-picker# has no selected value and the dropdown is opened, it automatically scrolls to the current month.
You can make it scroll to another month by setting the [propertyname]#initialPosition# property to a date in that month.

When [vaadinelement]#vaadin-date-picker# already has a value selected, opening the dropdown always scrolls to the month with the selected date.

[source,html]
----
<vaadin-date-picker initial-position="2020-05-01"></vaadin-date-picker>
----
