/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/vaadin-date-picker-light.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

import {ThemableMixin} from '@vaadin/vaadin-themable-mixin/vaadin-themable-mixin.js';

import {DatePickerMixin} from './vaadin-date-picker-mixin.js';

import {html} from '@polymer/polymer/lib/utils/html-tag.js';

import {dashToCamelCase} from '@polymer/polymer/lib/utils/case-map.js';

/**
 * `<vaadin-date-picker-light>` is a customizable version of the `<vaadin-date-picker>` providing
 * only the scrollable month calendar view and leaving the input field definition to the user.
 *
 * To create a custom input field, you need to add a child element which has a two-way
 * data-bindable property representing the input value. The property name is expected
 * to be `bindValue` by default. See the example below for a simplest possible example
 * using an `<input>` element extended with `iron-input`.
 *
 * ```html
 * <vaadin-date-picker-light>
 *   <iron-input>
 *     <input/>
 *   </iron-input>
 * </vaadin-date-picker-light>
 * ```
 *
 * If you are using other custom input fields like `<paper-input>`, you
 * need to define the name of value property using the `attrForValue` property.
 *
 * ```html
 * <vaadin-date-picker-light attr-for-value="value">
 *   <paper-input label="Birthday">
 *   </paper-input>
 * </vaadin-date-picker-light>
 * ```
 *
 * ### Styling
 *
 * The following shadow DOM parts are available for styling:
 *
 * Part name | Description | Theme for Element
 * ----------------|----------------|----------------
 * `overlay-content` | The overlay element | vaadin-date-picker-light
 *
 * See [ThemableMixin – how to apply styles for shadow parts](https://github.com/vaadin/vaadin-themable-mixin/wiki)
 *
 * In addition to `<vaadin-date-picker-light>` itself, the following
 * internal components are themable:
 *
 * - `<vaadin-date-picker-overlay>`
 * - `<vaadin-date-picker-overlay-content>`
 * - `<vaadin-month-calendar>`
 *
 * Note: the `theme` attribute value set on `<vaadin-date-picker-light>`
 * is propagated to the internal themable components listed above.
 */
declare class DatePickerLightElement extends
  ThemableMixin(
  DatePickerMixin(
  PolymerElement)) {
  _overlayInitialized: boolean;
  _inputValue: string|undefined;

  /**
   * Name of the two-way data-bindable property representing the
   * value of the custom input field.
   * @attr {string} attr-for-value
   */
  attrForValue: string;
  _input(): HTMLElement|null;
}

declare global {

  interface HTMLElementTagNameMap {
    "vaadin-date-picker-light": DatePickerLightElement;
  }
}

export {DatePickerLightElement};
